-- 20220626 일요일

-- 1. 테이블 스페이스 생성
CREATE TABLESPACE TBS_TEAM1
DATAFILE 'C:\TESTDATA\TBS_TEAM1.DBF'
SIZE 100M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;
--TABLESPACE TBS_TEAM1이(가) 생성되었습니다.


-- 2. 유저생성
CREATE USER TEAM1 IDENTIFIED BY java006$
DEFAULT TABLESPACE TBS_TEAM1;
--User TEAM1이(가) 생성되었습니다.


-- 권한 생성.
-- 3. 오라클 서버 접속 권한 부여
GRANT CREATE SESSION TO TEAM1;

-- 4. 테이블 생성 권한
GRANT CREATE TABLE TO TEAM1;

-- 테이블스페이스에서 쓸 수 있는 할당량? 제한 제거
ALTER USER TEAM1
QUOTA UNLIMITED ON TBS_TEAM1;

-- 계정 잠금 해제
ALTER USER TEAM1 ACCOUNT UNLOCK;

-- 뷰 권한
GRANT CREATE VIEW TO TEAM1;

-- 트리거 생성 권한
GRANT CREATE TRIGGER TO TEAM1;

-- 프로시저 생성 권한
GRANT CREATE PROCEDURE TO TEAM1;

-- 시퀀스 생성 권한
GRANT CREATE SEQUENCE TO TEAM1;

