-- MEMBER 테이블 데이터 확인 (왜 홍체리가 유저아이디가 4번인가)
SELECT *
FROM MEMBER
ORDER BY 1;
/*
0	0	2022-06-23
1	0	2022-06-23
2	1	2022-06-23
3	1	2022-06-23
4	1	2022-06-26
*/

-- PROFILE 테이블 데이터 확인(왜 MyPageMainController.java 진입이 안되는가 user_id 4로 받아가는데)
SELECT *
FROM PROFILE;

-- 이메일,닉네임, 한마디, 이미지 주소 조회
SELECT USER_ID,EMAIL,NICKNAME,ONEWORD,PI_ADDRESS
FROM VIEW_MYPAGEMAIN
WHERE USER_ID = 4;

--리더퀘스쳔 조회
SELECT QUESTION_ID , QU_CONTENT
FROM QUESTION;


-- 평가를 위한 라이딩 모임 일자 바꾸기
SELECT *
FROM RIDING;

-- 수정
UPDATE RIDING
SET START_DATE = TO_DATE('2022/06/17','YYYY.MM.DD')
WHERE RIDING_ID = 58;
-- 수정
UPDATE RIDING
SET END_DATE = TO_DATE('2022/06/18','YYYY.MM.DD')
WHERE RIDING_ID = 58;

--확인
SELECT *
FROM RIDING;

--커밋
COMMIT;


--현재 속한 RIDING 조회

SELECT TEMP.RIDING_ID
FROM
(
    SELECT ROW_NUMBER() OVER (ORDER BY R.END_DATE DESC) AS ROW1,R.*
    FROM RIDING R JOIN PARTICIPATED_MEMBER PM
    ON R.RIDING_ID = PM.RIDING_ID
    WHERE SYSDATE >= END_DATE+7/24 AND PM.USER_ID = 6
)TEMP
WHERE TEMP.ROW1 = 1;

-- RIDING 참여자 명단 출력
SELECT *
FROM PARTICIPATED_MEMBER;

-- USER_ID 7을 참여시키기
INSERT INTO PARTICIPATED_MEMBER
VALUES(SEQ_PARTICIPATED_MEMBER.NEXTVAL, 7,58,SYSDATE);

COMMIT;

-- 응답 테이블 DELETE



DELETE
FROM ANSWER_DETAIL_LEADERSHIP;

DELETE
FROM ANSWER_DETAIL;


DELETE
FROM ANSWER_ATTENDANCE;


DELETE
FROM CHECK_ATTENDANCE;

DELETE
FROM ANSWER;

COMMIT;





--방장이 평가한 폼 데이터 조회
SELECT *
FROM ANSWER;

SELECT *
FROM CHECK_ATTENDANCE;

SELECT *
FROM ANSWER_ATTENDANCE;

SELECT *
FROM ANSWER_DETAIL;



--멤버가 평가한 폼 데이터 조회
SELECT *
FROM ANSWER;

SELECT *
FROM CHECK_ATTENDANCE;

SELECT *
FROM ANSWER_ATTENDANCE;

SELECT *
FROM ANSWER_DETAIL;

SELECT *
FROM ANSWER_DETAIL_LEADERSHIP;


-- question 테이블 조회
SELECT *
FROM QUESTION;

SELECT QUESTION_ID
FROM QUESTION
WHERE QU_CONTENT = 'GOOD';


SELECT *
FROM ANSWER_DETAIL_LEADERSHIP;

DESC ANSWER_DETAIL_LEADERSHIP;

-- 수동으로 리더십 데이터 넣어보기

--1. ANSWER_ID 찾기
SELECT ANSWER_ID
FROM
(
SELECT  ROWNUM AS ANSROW,ANSWER_ID
        FROM PARTICIPATED_MEMBER PM JOIN ANSWER A
        ON PM.PA_MEMBER_ID = A.PA_MEMBER_ID
        WHERE PM.USER_ID = 7
)TEMP
WHERE TEMP.ANSROW=1;

INSERT INTO ANSWER_DETAIL_LEADERSHIP(ANS_L_ID,ANSWER_ID,QUESTION_ID,ANS_CONTENT)
VALUES(SEQ_ANSWER_DETAIL_LEADERSHIP.NEXTVAL, 49, 4,'GOOD');