-- 전체적으로 P_MEMBER_ID >> PA_MEMBER_ID 변경
ALTER TABLE ANSWER_DETAIL RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE ANSWER RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE ANSWER_ATTENDANCE RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE CHECK_ATTENDANCE RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE EVALUATION_RECORD RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE ABSCOND RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE PARTICIPATED_MEMBER RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE RIDING_RECORD RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

-----------------------------------------------------------------------------

-- 06/23 두 번째
-- 프로필 모든 데이터 삭제
DELETE
FROM PROFILE

COMMIT;

-- FK 삭제
ALTER TABLE RIDING
DROP CONSTRAINT FK_AGE_PREFERENCE_TO_RIDING_1;

ALTER TABLE RIDING
DROP CONSTRAINT FK_SEX_PREFERENCE_TO_RIDING_1;

ALTER TABLE PROFILE
DROP CONSTRAINT FK_AGE_PREFERENCE_TO_PROFILE_1;

ALTER TABLE PROFILE
DROP CONSTRAINT FK_SEX_PREFERENCE_TO_PROFILE_1;
------------------------------------------------

-- 데이터 타입 변경
DELETE
FROM SEX_PREFERENCE;

ALTER TABLE SEX_PREFERENCE MODIFY SEX_P_ID NUMBER(1);

INSERT INTO SEX_PREFERENCE (SEX_P_ID, SP_CONTENT)
VALUES (0, '제한없음');

INSERT INTO SEX_PREFERENCE (SEX_P_ID, SP_CONTENT)
VALUES (1, '남자');

INSERT INTO SEX_PREFERENCE (SEX_P_ID, SP_CONTENT)
VALUES (2, '여자');

DELETE
FROM AGE_PREFERENCE;

ALTER TABLE AGE_PREFERENCE MODIFY AGE_P_ID NUMBER(1);

INSERT INTO AGE_PREFERENCE (AGE_P_ID, AP_CONTENT)
VALUES (0, '제한없음');

INSERT INTO AGE_PREFERENCE (AGE_P_ID, AP_CONTENT)
VALUES (1, '10대');

INSERT INTO AGE_PREFERENCE (AGE_P_ID, AP_CONTENT)
VALUES (2, '20대');

INSERT INTO AGE_PREFERENCE (AGE_P_ID, AP_CONTENT)
VALUES (3, '30대');

INSERT INTO AGE_PREFERENCE (AGE_P_ID, AP_CONTENT)
VALUES (4, '40대');

INSERT INTO AGE_PREFERENCE (AGE_P_ID, AP_CONTENT)
VALUES (5, '50대');

INSERT INTO AGE_PREFERENCE (AGE_P_ID, AP_CONTENT)
VALUES (6, '60대 이상');

COMMIT;

-- 
ALTER TABLE PROFILE MODIFY AGE_P_ID NUMBER(1);
ALTER TABLE PROFILE MODIFY SEX_P_ID NUMBER(1);
-- 변경

ALTER TABLE RIDING MODIFY AGE_P_ID NUMBER(1);
ALTER TABLE RIDING MODIFY SEX_P_ID NUMBER(1);
-- 변경

--------------------------------------------------

ALTER TABLE PROFILE ADD CONSTRAINT CHECK_SEX CHECK(SEX IN('M', 'F'));
-- Table PROFILE이(가) 변경되었습니다.

ALTER TABLE PROFILE ADD CONSTRAINT CHECK_MOOD CHECK(MOOD_P_ID IN(0, 1, 2));
-- 변경

ALTER TABLE PROFILE ADD CONSTRAINT CHECK_EAT CHECK(EAT_P_ID IN(0, 1, 2));
-- 변경

ALTER TABLE PROFILE ADD CONSTRAINT CHECK_DINING CHECK(DINING_P_ID IN(0, 1, 2));
-- 변경

ALTER TABLE PROFILE ADD CONSTRAINT CHECK_SEX_P CHECK(SEX_P_ID IN(0, 1, 2));
-- 변경

ALTER TABLE PROFILE ADD CONSTRAINT CHECK_AGE_P CHECK(AGE_P_ID IN(0, 1, 2, 3, 4, 5, 6));
-- 변경

ALTER TABLE PROFILE
DROP CONSTRAINT CHECK_SEX_P;
-- 변경

ALTER TABLE PROFILE
DROP CONSTRAINT CHECK_AGE_P;
-- 변경

-- USER 권한 관련 제약조건
ALTER TABLE MEMBER ADD CONSTRAINT CHECK_ACCESS CHECK(ACCESS_ID IN(0, 1));
-- 변경


-- 모임 참여자 신고처리 관련 제약조건
ALTER TABLE PARTICIPANT_REPORT_PROCESS ADD CONSTRAINT CHECK_PROC_STATUS CHECK(PROC_STATUS_ID IN(1, 2, 3));
-- 변경

-- 모임참여자 패널티부여 관련 제약 조건
ALTER TABLE PARTICIPANT_PENALTY ADD CONSTRAINT CHECK_PENALTY_TYPE CHECK(PENALTY_TYPE_ID IN(1, 2));
-- 변경



-- 다인 라이딩 속성 관련 제약 조건
ALTER TABLE RIDING ADD CONSTRAINT CHECK_STEP CHECK(STEP_ID IN(0, 1, 2, 3, 4));
-- 변경

ALTER TABLE RIDING ADD CONSTRAINT CHECK_SPEED CHECK(SPEED_ID IN(0, 1, 2, 3));
-- 변경

ALTER TABLE RIDING ADD CONSTRAINT CHECK_MOOD_R CHECK(MOOD_P_ID IN(0, 1, 2));
-- 변경

ALTER TABLE RIDING ADD CONSTRAINT CHECK_DINING_R CHECK(DINING_P_ID IN(0, 1, 2));
-- 변경

ALTER TABLE RIDING ADD CONSTRAINT CHECK_EAT_R CHECK(EAT_P_ID IN(0, 1, 2));
-- 변경

ALTER TABLE RIDING ADD CONSTRAINT CHECK_GRADE CHECK(EV_GRADE_ID IN(0, 1, 2, 3, 4, 5));
-- 변경

ALTER TABLE RIDING ADD CONSTRAINT CHECK_AGE_R CHECK(AGE_P_ID IN(0, 1, 2, 3, 4, 5, 6));

ALTER TABLE RIDING ADD CONSTRAINT CHECK_SEX_R CHECK(SEX_P_ID IN(0, 1, 2));



SELECT *
FROM PROFILE;

ALTER TABLE RIDING
DROP CONSTRAINT CHECK_AGE_R;

SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='PROFILE';



ALTER TABLE PROFILE
ADD CONSTRAINT FK_AGE_PREFERENCE_PROFILE FOREIGN KEY(AGE_P_ID) REFERENCES AGE_PREFERENCE(AGE_P_ID);

ALTER TABLE PROFILE
ADD CONSTRAINT FK_SEX_PREFERENCE_PROFILE FOREIGN KEY(SEX_P_ID) REFERENCES SEX_PREFERENCE(SEX_P_ID);


ALTER TABLE RIDING
ADD CONSTRAINT FK_AGE_PREFERENCE_RIDING FOREIGN KEY(AGE_P_ID) REFERENCES AGE_PREFERENCE(AGE_P_ID);

ALTER TABLE RIDING
ADD CONSTRAINT FK_SEX_PREFERENCE_RIDING FOREIGN KEY(SEX_P_ID) REFERENCES SEX_PREFERENCE(SEX_P_ID);


COMMIT;



