-- 전체적으로 P_MEMBER_ID >> PA_MEMBER_ID 변경
ALTER TABLE ANSWER_DETAIL RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE ANSWER RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE ANSWER_ATTENDANCE RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE CHECK_ATTENDANCE RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE EVALUATION_RECORD RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE ABSCOND RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE PARTICIPATED_MEMBER RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

ALTER TABLE RIDING_RECORD RENAME COLUMN P_MEMBER_ID TO PA_MEMBER_ID;

-----------------------------------------------------------------------------

